### ISSUE TITLE
graphviz not optional?

### ISSUE THREAD

**Issue by stetner** [grocsvs/grocsvs#7]
Hi,

I am trying to install without graphviz as it will not compile on my centos6.9 box, but get a failure on pygraphviz.  So not really 'optional'??

Thanks,

    creating build/temp.linux-x86_64-2.7/pygraphviz
    /opt/Modules/gcc/5.2.0/bin/gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/pkg/2015Q2/include/graphviz -I/shares/common/users/d.stetner/build/anac/include/python2.7 -c pygraphviz/graphviz_wrap.c -o build/temp.linux-x86_64-2.7/pygraphviz/graphviz_wrap.o
    pygraphviz/graphviz_wrap.c:2954:29: fatal error: graphviz/cgraph.h: No such file or directory
     #include "graphviz/cgraph.h"
                                 ^
    compilation terminated.
    error: command '/opt/Modules/gcc/5.2.0/bin/gcc' failed with exit status 1

**Comment by nspies** [comment]
This is an unfortunate issue with python packaging -- there isn't a simple way to instruct a package to be installed if possible but continue if it fails. As you seem to have noted, removing pygraphviz from the setup.py requirements will allow you to install fine without pygraphviz/graphviz and I'm pretty sure everything will also run okay without them though the graphs describing complex events won't be visualized.

I'll update the readme to indicate that graphviz needs to be installed for pygraphviz to work.

For what it's worth, I think there should be an rpm of graphviz for your version of centos that would work. Haven't tried it myself, though.

**Comment by nspies** [comment]
closed by a927727aab0d7be9f6f2ef0d11256be0d6c0b3dc
